//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInStock
    {
        public int id { get; set; }
        public int idProduct { get; set; }
        public int idStock { get; set; }
        public int amountMin { get; set; }
        public int amountMax { get; set; }
        public int amountCurrent { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
